### ISSUE TITLE
Pickaxe unable to break blocks

### ISSUE THREAD

**Issue by cheeseboyreal** [YerovaArusu/botanicpledge#11]
Hey I noticed that with the new update vanilla tools like an iron pickaxe are unable to properly break blocks. If there is anything else you need me to clarify I would be happy too.

**Comment by YerovaArusu** [comment]
In my test environment this should be fixed now. Later today i will publish a small update fixing this.

**Comment by cheeseboyreal** [comment]
thanks a ton
