### ISSUE TITLE
Equmpents bugs

### ISSUE THREAD

**Issue by EnotScript** [YerovaArusu/botanicpledge#14]
Core doing nothing.
![image](https://github.com/user-attachments/assets/efa7840d-77ef-4dc4-a108-1439678ea465)

Helmet have 374 durability.
![image](https://github.com/user-attachments/assets/f69c4c51-aa71-40a7-b9b4-6f9c66d5c3d6)

The armor charge Terrashutter or similar from Mythic or Aiot and prevents digging.

**Comment by YerovaArusu** [comment]
Sorry? I dont fully understand the problems?

1. Regarding the Core doing nothing: You currently need a Mana Tablet in the inventory...
2. Regarding the durability: The durability is supposed to be like that (Its the same as Terra-steel). I will consider improving it.
3. I dont understand what you are talking about? can you please elaborate?

I hope this clears up some stuff

**Comment by EnotScript** [comment]
I have mana tablet + mana mirror.  No fly, no protect.

Only helmet have low durability other 6400

Armor generates mana regardless of how many pieces are worn. It generates mana in the Terrashutter and in the improved versions from other mods, constantly updating and not allowing digging. + not work, WILL from Gaia.

**Comment by YerovaArusu** [comment]
Okay. Do you have any error logs or similar? So that I know where to check?

**Comment by EnotScript** [comment]
[latest.log](https://github.com/user-attachments/files/17356389/latest.log)
only logs not have debug

**Comment by YerovaArusu** [comment]
It really is weird that this is not working for you... I just created a new Modpack and testet it out... I just added a few mods like apotheosis, Botania and Expanded Combat... but my I dont have any Issues... 

Regarding the durability issue on the helmet: I fixed it.

Which version of this mod are you using?


![image](https://github.com/user-attachments/assets/025acafc-a61c-4724-b1dd-4b0dd2b88897)

**Comment by EnotScript** [comment]
Forge 1.20.1 0.7.3

Atm 9-no frills - lastest

**Comment by YerovaArusu** [comment]
Hmm... I am sorry... I don't know how to fix the issue with the core not working in your modpack... Are you using a custom modpack or an official modpack?

**Comment by EnotScript** [comment]
Mana buffer not works too

**Comment by YerovaArusu** [comment]
The Mana Buffer works as intended. I just testet it in ATM-No frills. In the following you can see the way the mana buffer is used.

And in this Modpack there definetly is an incomaptibility with the core item since the shieldbar is not rendered. But flying works without an issue

The bottom 4 Mana pools are the input and the top Pool is the output. (See the image)

![image](https://github.com/user-attachments/assets/b28a98ca-9206-4d5e-b9d2-8a0f38538a2f)

**Comment by EnotScript** [comment]
Ok buffer works fine. My bad. 
But flying not. Idk why. Im took everything off himself, leaving only the core and the mana tablet.

**Comment by YerovaArusu** [comment]
I made some minor changes to my mod. Can you maybe test if this works?
It only has some smaller changes. You should not lose anything when testing this mod.

And can you make sure that this curios really is in the right slot? It should NOT be in the "curios" slot. It should be in the "divine core" slot.

This is not an official release. Because of this its not yet available on Curseforge
Unpack this Zip here for the mod:
[botanicpledge-1.20.1-0.7.3.1.zip](https://github.com/user-attachments/files/17368428/botanicpledge-1.20.1-0.7.3.1.zip)

**Comment by EnotScript** [comment]
![image](https://github.com/user-attachments/assets/bc2fd6f8-2729-44c5-910d-a4fd0d30277b)
yes in core slot

0 changes

**Comment by EnotScript** [comment]
![image](https://github.com/user-attachments/assets/93963e93-3593-4cab-9eb9-9019971d4dd0)

thats all

**Comment by YerovaArusu** [comment]
Okay... I understand.
1. Are you using this on a server or on a single player world?
2. Can you maybe test in a different world if that error is still present?

**Comment by EnotScript** [comment]
Singleplayer+lan (im host)
In another world problem not solved.

**Comment by YerovaArusu** [comment]
Hmm... Okay... You said you are using the modpack "ATM-No frills" and you added my mod additionaly. Are there any other mods you added?
Oh and: what version of 'ATM - No frills' are you using? I am using version 0.1.17.

**Comment by EnotScript** [comment]
Same version
botanicpledge-1.20.1-0.7.3.1.jar
ProjectRed-1.20.1-4.19.0 full
clockwork-1.20.1-0.1.16-forge-b3b22e39fe.jar
valkyrienskies-120-2.3.0-beta.5
radiantgear-forge-2.1.5+1.20.1
Vampirism-1.20.1-1.10.10.jar
aiotbotania-1.20.1-4.0.5.jar
BotanicalMachinery-1.20.1-3.0.4.jar

**Comment by YerovaArusu** [comment]
okay. I am currently in the process of testing which mod creates that error. I currently know that one of these mods is incompatible with my mod

**Comment by YerovaArusu** [comment]
Okay. After some tests it seems that there is some incomatibility with Vampirism.
When i installed all the mods flying did not work. But after removing Vampirism I could fly again. I tested it multiple times to make sure that Vampirism really was the issue.

Maybe you can test it on your end (in a test world ) as well

**Comment by EnotScript** [comment]
Since it is already 4 am, I will be able to check in the afternoon.

**Comment by YerovaArusu** [comment]
Have you been able to test if vampirism is causing the issue on your end as well?

**Comment by EnotScript** [comment]
Yes, I checked. The problem does not go away.

**Comment by EnotScript** [comment]
Vampirism - does not affect anything.
More than 3 hours of checking found 4 conflicting mods..... and that's not all

**Comment by EnotScript** [comment]
cfm-forge-1.20.1-7.0.0-pre36.jar
copycats-2.1.4+mc.1.20.1-forge.jar
cozy_home-3.0.4-forge-1.20.1.jar
creeperoverhaul-3.0.2-forge.jar
FpsReducer2-forge-1.20-2.5.jar
createdieselgenerators-1.20.1-1.2i.jar
majrusz-library-forge-1.20.1-7.0.8.jar
majruszs-accessories-forge-1.20.1-1.5.3.jar

Macaw 1 or more idk  ( mcw-bridges-3.0.0-mc1.20.1forge.jar , mcw-doors-1.1.1forge-mc1.20.1.jar , mcw-furniture-3.3.0-mc1.20.1forge.jar , mcw-holidays-1.1.0-mc1.20.1forge.jar , mcwifipnp-1.7.3-1.20.1-forge.jar , mcw-lights-1.1.0-mc1.20.1forge.jar , mcw-paths-1.0.5-1.20.1forge.jar , mcw-roofs-2.3.1-mc1.20.1forge.jar , mcw-trapdoors-1.1.3-mc1.20.1forge.jar , mcw-windows-2.3.0-mc1.20.1forge.jar

After so much time I'm just tired of checking every mod... Maybe there are still conflicts out of 9...


dummmmmmy-1.20-2.0.2.jar
fairylights-7.0.0-1.20.1.jar
fantasyfurniture-1.20.1-9.0.0.jar
nightlights-1.20.1-1.1.jar
radiantgear-forge-2.1.5+1.20.1.jar
tfmg-0.9.2-1.20.1.jar
touhoulittlemaid-1.20.1-release-1.1.12-hotfix2.jar
vintageimprovements-1.20.1-0.2.0.3.jar
wardrobe-1.0.3.1-forge-1.20.1.jar

                                                                                                                                               Good luck

**Comment by YerovaArusu** [comment]
I am honestly really wondering why you are encountering this issue...

Its really weird that i cant completely replicate your error...

I am currently looking through other mods, where flying abilities work.
I am looking at their code and try to understand what i am doing different... but there is not much different...

For example Angel Rings 2 (https://github.com/DenisMasterHerobrine/AngelRing/tree/master) is doing pretty similar stuff...
thats why i am even more confused.

**Comment by YerovaArusu** [comment]
Another question: if you use a default instance of the ATM - no frills modpack with only my mod added, is the issue also present there?

**Comment by EnotScript** [comment]
By default, everything with core is fine.

**Comment by EnotScript** [comment]
I also discovered that the Rune Tablet of Fimbultyr from the MythicBotany mod does not drop when botanicpledge is installed.

**Comment by YerovaArusu** [comment]
Where does that rune drop from? From Gaia II?

**Comment by EnotScript** [comment]
yes

**Comment by YerovaArusu** [comment]
Okay. I already know why that error is happening. I will fix it in the next 24 hours
