### ISSUE TITLE
Pedestal break drop no hold items

### ISSUE THREAD

**Issue by Reaviik** [YerovaArusu/botanicpledge#23]
**Describe the bug**

**To Reproduce**
1. Place an pedestal
2. Put a random item
3. Break the pedestal
4. Nice, has no item more

**Expected behavior**
Drop the pedestal item hold

**Affected version**
- Mod version = 1.20.1-0.7.4.1
- Forge version 47.3.0
- Minecraft version 1.20.1

**Environment:**
- Private modpack sorry

**Comment by YerovaArusu** [comment]
In the next version releasing this issue will be fixed. I will propably release it on sunday.
