### ISSUE TITLE
Vedrfolnir's Core 

### ISSUE THREAD

**Issue by EndilCrafter** [YerovaArusu/botanicpledge#24]
https://github.com/user-attachments/assets/ddd4c42a-2913-446d-96d2-b289db53f0af
Also, when I hold any item and press shift+V(interaction keybind), it has lore of First Relic.
![2024-12-08_09 05 34](https://github.com/user-attachments/assets/8f5f4750-3299-43fd-b96f-dcd6f829b6d9)

Version
- 1.20.1-0.7.4.1
- 47.3.12

Mods
- Botania
- Pledge
- Cloth Config API
- Curios
- JEI
- Patchouli

**Comment by YerovaArusu** [comment]
Thank you for pointing out these errors. They will be fixed with the release of the next version.

**Comment by EndilCrafter** [comment]
Sorry, I have an another question.
How do I use abilities of Vedrfolnir's Core?
I tried to fly, but couldn't. Shield won't be generated.
Whether I have a mana tablet or not, nothing changed.

**Comment by YerovaArusu** [comment]
regarding the flight: In theory it should work immediately. (even in my normal private modpack it works). Did you make sure to place it in the actual "Divine Core" Slot?
And the shield is only available after getting to the first level of the mana infusion. 
so... just charge it like you would charge a mana ring in a mana pool until the next level

**Comment by EndilCrafter** [comment]
Yes, I placed it in right slot and got over first level. But no changed.
However, abilities have enabled only once, but suddenly disabled.

**Comment by YerovaArusu** [comment]
Hmm... That really is weird... Do you have any more information? Because whatever I try it works for me...

**Comment by EndilCrafter** [comment]
https://github.com/user-attachments/assets/7df14cac-02e2-454d-9de9-8076ece4f6c3

**Comment by EndilCrafter** [comment]
Forge: 47.3.0 or 47.2.0 + Pledge: 0.7.4.1 -> no
Forge: 47.3.12 + Pledge: 0.7.4 -> success
Updated after successed -> success
My modpack(Endil's Expert Edition Extra) -> no

**Comment by EndilCrafter** [comment]
I deleted AttributeFix config and tried again. It successed.

**Comment by YerovaArusu** [comment]
So this really is a very weird bug. I will try looking into the issue but I can't guarantee any success. Do you maybe have some... Debug logs with some useful information? Or something else where I can check for the error?

**Comment by EndilCrafter** [comment]
![Desktop Screenshot 2024 12 09 - 14 23 01 18](https://github.com/user-attachments/assets/7a11ea4f-cf7e-47f7-bf08-a64b904c984c)
Now there is no information about error. But before deleting AF config, I found errors about missing attribute id(such as witherstormmod).
So I tried to delete config once, then Pledge core worked properly.

**Comment by EndilCrafter** [comment]
I made a new instance that uses only Pledge(+Botania, Curios, Patchouli)
Forge and mod version is latest.
First launch -> failure -> https://mclo.gs/xLw29KZ
Second launch without changes -> failure
Third launch with Attribute Fix -> success -> https://mclo.gs/uOMU3em

**Comment by YerovaArusu** [comment]
![image](https://github.com/user-attachments/assets/ad5eb19b-94dd-4c76-b9ca-0f3678849712)


This really is getting weirder by the minute. In this modpack i can fly using my the core item without any issues... 
And all of the errors in the log are not related to the Core Item.

**Comment by EndilCrafter** [comment]
I see. I could fly with above instance.
When I removed Architectury, Cloth, JEI, and LibX, I couldn't fly.
But I could in second launch.

**Comment by YerovaArusu** [comment]
![image](https://github.com/user-attachments/assets/41db11c4-030c-4902-b986-239fb422433f)
its really weird. i now also removed said mods and everything is working completely fine
