### ISSUE TITLE
[1.20.1]Crash report

### ISSUE THREAD

**Issue by Git-Reternos** [YerovaArusu/botanicpledge#26]
**Describe the bug**
Crash when start up

**To Reproduce**

**Expected behavior**

**Screenshots**

**Affected version**
- Mod version 1.20.1-0.8
- Forge version 47.3.22
- Minecraft version 1.20.1

**Environment:**
- Additional mods used
- Modpack name if its a public modpack

**Logs**
[crash-2024-12-24_17.09.44-client.txt](https://github.com/user-attachments/files/18238056/crash-2024-12-24_17.09.44-client.txt)

**Additional context**

**Comment by YerovaArusu** [comment]
Does this error occur on every start-up or just sometimes?

**Comment by Git-Reternos** [comment]
Every start-up( i already tried 10 times)

**Comment by YerovaArusu** [comment]
Hmm... Okay. Later today (in 3 hours) I will give you a special test version. Can you then tell me if the error is fixed?

**Comment by Git-Reternos** [comment]
i need go sleep later so i cant reply you until tomorrow

**Comment by YerovaArusu** [comment]
Hmm okay. Then give me 5min.

**Comment by YerovaArusu** [comment]
Here is the zip with the test file. If this doesnt work, then i will copntinue working on it later. (I am currently still at work thats why i only have limited time right now)
[botanicpledge-1.20.1-0.8_ZIP.zip](https://github.com/user-attachments/files/18239112/botanicpledge-1.20.1-0.8_ZIP.zip)

**Comment by Git-Reternos** [comment]
it working

**Comment by YerovaArusu** [comment]
Okay. Thank you then I will close this issue now that it's working
