### ISSUE TITLE
Vedrfolnir`s core doesn't have curios slot attribute

### ISSUE THREAD

**Issue by EnotScript** [YerovaArusu/botanicpledge#5]
![image](https://github.com/YerovaArusu/botanicpledge/assets/78641086/45935f95-6b9a-464e-b94a-7a63ad181b74)

**Comment by YerovaArusu** [comment]
verision 0.6.3.1 should fixes this issues. In a few minutes it should be available on CurseForge

So I will mark this issue as closed. If there are other errors then let me know asap

![image](https://github.com/YerovaArusu/botanicpledge/assets/90931045/bbc7157d-a765-4c90-a153-8af954099215)
