### ISSUE TITLE
Ring of Aesir + LMB bug + Vedrfolnir's Core

### ISSUE THREAD

**Issue by EnotScript** [YerovaArusu/botanicpledge#6]
1. The Loki ring function does not work.

2. Odin doesn't work either. But Terra Shatterer without a ring alone works as with it. Putting on the Aesir ring does not change anything.

3. The Odin ring effect does not work on earth crushers from other mods. for example MythicBotany, AIOT Botania. Possibly related to point 2.

4. If you have mana, pressing LMB with an item in your hand will teleport in the direction of the cursor.

5. Vedrfolnir's Core - Sources of damage such as cactus, lava, magma, fire, etc. They damage the core at such a rate that any possible mana is destroyed.

**Comment by YerovaArusu** [comment]
I am gonna work on them ASAP. but today i wont be able to finish it. 
I already fixed the last two points. 
Thank you for telling me about the issues. Please leave any other errors you might run into here as well.

**Comment by YerovaArusu** [comment]
I am thinking of removing the Loki and thor abilities from the ring of aesir because it is way to difficult to integrate everything into  Botania. 
I am not completely sure yet, but it could happen

**Comment by YerovaArusu** [comment]
All of the issues are fixed in the currently processing version (1.20.1-0.6.3.2). It should be available in half an hour.
I will close this issue now. 
Please report any further issues ASAP and i will try to fix them ASAP.
