### ISSUE TITLE
Server Crash 

### ISSUE THREAD

**Issue by Reaviik** [YerovaArusu/botanicpledge#8]
According to server players, the crash occurs when they receive some type of damage.
[crash-2024-06-28_18.18.58-server.txt](https://github.com/user-attachments/files/16042081/crash-2024-06-28_18.18.58-server.txt)
[crash-2024-06-28_17.02.07-server.txt](https://github.com/user-attachments/files/16042082/crash-2024-06-28_17.02.07-server.txt)

**Comment by YerovaArusu** [comment]
On my end I tried my best to fix this issue. It didnt occur again. So now I will now publish this new version to Curseforge and close this issue. If this issue is still present after using the new version please reopen this issue
