### ISSUE TITLE
Recipe Error

### ISSUE THREAD

**Issue by Reaviik** [YerovaArusu/botanicpledge#9]
I'm trying to make Mundo dos Ramos, but the recipe doesn't seem like it, this happens with the last update.

If possible, can you send me the json of the recipe so that I can put it in Kubejs without having to update the modpack. ^^
[Book Recipe](https://prnt.sc/x75Tk3QBwWQk)

**Comment by YerovaArusu** [comment]
Hello there. The Recipe was indeed removed. This is not a bug/error. It is a feature.

The one responsible for the Lexica botania sadly did not have not enough time to change it when I was releasing the update.

In the last update i removed that recipe. Now you can only obtain "World Ash Branches" by chopping livingwood with an axe which has the new Enchantment "yggdrasil debarking bounty". The enchance is equal to the enchantment level. so:

lv 1-> 1%
lv 2 -> 2%
lv 3 -> 3%
.
.
.

![image](https://github.com/YerovaArusu/botanicpledge/assets/90931045/d7f134ba-3b89-4077-bee0-4af510194409)

**Comment by Reaviik** [comment]
aaaaah, ok thanks for clarifying ^^ I'm grateful
